In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
sns.axes_style("white")

{'figure.facecolor': 'white',
 'axes.labelcolor': '.15',
 'xtick.direction': 'out',
 'ytick.direction': 'out',
 'xtick.color': '.15',
 'ytick.color': '.15',
 'axes.axisbelow': True,
 'grid.linestyle': '-',
 'text.color': '.15',
 'font.family': ['sans-serif'],
 'font.sans-serif': ['Arial',
  'DejaVu Sans',
  'Liberation Sans',
  'Bitstream Vera Sans',
  'sans-serif'],
 'lines.solid_capstyle': 'round',
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'image.cmap': 'rocket',
 'xtick.top': False,
 'ytick.right': False,
 'axes.grid': False,
 'axes.facecolor': 'white',
 'axes.edgecolor': '.15',
 'grid.color': '.8',
 'axes.spines.left': True,
 'axes.spines.bottom': True,
 'axes.spines.right': True,
 'axes.spines.top': True,
 'xtick.bottom': False,
 'ytick.left': False}

In [13]:
def show_lineplot(df, hue='model', x='iteration', y='item_rank', xlabel='Iteration', ylabel='Item Rank', name="item_rank_iteration", save=True):
    fig, ax = plt.subplots(figsize=(6, 3))
#     df = df.sort_values(by=['model'])
    #plt.axhline(y=0.165, color='r', linestyle='-')
    ax = sns.lineplot(x=x, y=y, hue=hue, style=hue, data=df, ci=68)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    handles, labels = ax.get_legend_handles_labels()
    ax.legend(handles=handles[1:], labels=labels[1:])
    plt.tight_layout()
    if save:
        fig_path = load_yaml('config/global.yml', key='path')['figs']
        fig.savefig('{0}/{1}.pdf'.format(fig_path, name),
                    bbox_inches="tight", pad_inches=0, format='pdf')
    else:
        plt.show()

def show_barplot(df, hue='Model', x='target_rank', y='Popularity', xlabel='Target Rank', ylabel='Popularity', name="item_pop", save=True):
    fig, ax = plt.subplots(figsize=(6, 3))
    df = df.sort_values(by=['Model'])
    #plt.axhline(y=0.165, color='r', linestyle='-')
#    ax = sns.barplot(y=x, x=y, hue=hue, data=df, orient='h', ci=68)
#    ax = sns.barplot(x=x, y=y, hue=hue, data=df, ci=68)
#    ax = sns.boxplot(x=x, y=y, hue=hue, data=df)
    ax = sns.violinplot(x=x, y=y, hue=hue, data=df)

    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    handles, labels = ax.get_legend_handles_labels()
    ax.legend(handles=handles[:], labels=labels[0:])
#    ax.legend(handles=handles[1:], labels=labels[1:])
    plt.tight_layout()
    if save:
        fig_path = load_yaml('config/global.yml', key='path')['figs']
        fig.savefig('{0}/{1}.pdf'.format(fig_path, name),
                    bbox_inches="tight", pad_inches=0, format='pdf')
    else:
        plt.show()

In [14]:
def save_dataframe_csv(df, path, name):
    df.to_csv(path+name, index=False)


def load_dataframe_csv(path, name, index_col=None):
    return pd.read_csv(path+name, index_col=index_col)

In [42]:
table_path = '../tables/critiquing/multi_step_critiquing/yelp/avg/'
name = 'test_result_for_plotting1.csv'
df = load_dataframe_csv(table_path, name)

In [25]:
df['result']

0            NaN
1            NaN
2     successful
3            NaN
4     successful
         ...
90           NaN
91           NaN
92           NaN
93           NaN
94          fail
Name: result, Length: 95, dtype: object

In [27]:
df

,critiqued_keyphrase,item_id,item_name,item_rank,item_score,iteration,num_existing_keyphrases,result,target_rank,user_id,critiqued_keyphrase_name,lambda
0,NaN,78.0,b'The Works Gourmet Burger Bistro',NaN,NaN,0.0,20.0,NaN,200.0,0.0,NaN,NaN
1,48.0,78.0,b'The Works Gourmet Burger Bistro',445.0,0.146624,1.0,20.0,NaN,200.0,0.0,burger,[1]
2,4.0,78.0,b'The Works Gourmet Burger Bistro',90.0,0.296639,2.0,20.0,successful,200.0,0.0,fry,"[1, 1]"
3,NaN,623.0,b'El Rey Mezcal Bar',NaN,NaN,0.0,20.0,NaN,200.0,0.0,fry,"[1, 1]"
4,58.0,623.0,b'El Rey Mezcal Bar',136.0,0.366992,1.0,20.0,successful,200.0,0.0,cocktail,[1]
...,...,...,...,...,...,...,...,...,...,...,...,...
90,125.0,6524.0,b'Constantine',1820.0,0.165119,16.0,20.0,NaN,200.0,0.0,pasta,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
91,151.0,6524.0,b'Constantine',1833.0,0.168146,17.0,20.0,NaN,200.0,0.0,busy,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
92,153.0,6524.0,b'Constantine',1880.0,0.171582,18.0,20.0,NaN,200.0,0.0,friendly,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
93,183.0,6524.0,b'Constantine',2367.0,0.114346,19.0,20.0,NaN,200.0,0.0,attentive,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
94,215.0,6524.0,b'Constantine',1717.0,0.185312,20.0,20.0,fail,200.0,0.0,sour,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [37]:
def avg_successful_rate(df):
    num_runs = len(np.where(df['iteration'] == 0)[0])
    num_success = len(np.where(df['result'] == 'successful')[0])
    
    return num_success/num_runs

In [40]:
def avg_length(df,include_fail = True):
    num_runs = len(np.where(df['iteration'] == 0)[0])
    return len(df)/num_runs

In [43]:
avg_length(df)

10.885542168674698

In [44]:
avg_successful_rate(df)

0.6325301204819277

In [ ]:
df_20 = df[df['target_rank'] == 20]